version: '3'

volumes:
  postgres_keycloak:
    driver: local
  postgres_stocksimapi:
    driver: local

services:

  postgres-keycloack:
    image: postgres:13-alpine
    volumes:
      - postgres_keycloak:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: pro
      POSTGRES_PASSWORD: pro

  keycloak:
    container_name: stockSim-keycloak
    image: srpoe/stocksimkeycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloack
      DB_DATABASE: keycloak
      DB_USER: pro
      DB_SCHEMA: public
      DB_PASSWORD: pro
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: "QBgrqwWfR44xcRgy"
      RABBITMQ.HOST: rabbitmq
      RABBITMQ.USER: "admin"
      RABBITMQ.PASSWORD: "{<BX>Q9samX3"
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/tmp/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - 8080:8080
    depends_on:
      - postgres-keycloack
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: "{<BX>Q9samX3"
    ports:
      - 5672:5672
      - 15672:15672

  postgres-stocksim:
    image: postgres:13-alpine
    volumes:
      - postgres_stocksimapi:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: stocksim
      POSTGRES_USER: pro
      POSTGRES_PASSWORD: pro

  stocksim-api:
    image: srpoe/stocksimapi
    ports:
      - 8070:80
    environment:
      my.keycloak.container.name: "stockSim-keycloak"
      my.postgres.container.name: "postgres-stocksim"
      my.serverregistry.container.port: "80"
      my.serverregistry.container.name: "stocksim-server-registry"
      my.rabbitmq.container.name: "rabbitmq"
      spring.rabbitmq.username: admin
      spring.rabbitmq.password: "{<BX>Q9samX3"
    depends_on:
      - keycloak
      - postgres-stocksim
      - rabbitmq
      - stocksim-email
      - stocksim-server-registry

  stocksim-email:
    image: srpoe/stocksimemail
    ports:
      - 8090:80
    environment:
      spring.mail.host: "YOUR SMTP EMAIL"
      spring.mail.username: "YOUR EMAIL "
      spring.mail.password: "YOUR EMAIL PASSWORD"
      my.serverregistry.container.port: "80"
      my.serverregistry.container.name: "stocksim-server-registry"
      my.rabbitmq.container.name: "rabbitmq"
      spring.rabbitmq.username: admin
      spring.rabbitmq.password: "{<BX>Q9samX3"
    depends_on:
      - keycloak
      - postgres-stocksim
      - rabbitmq
      - stocksim-server-registry

  stocksim-server-registry:
    image: srpoe/stocksimserverregistry
    ports:
      - 8100:80
