version: '3'

volumes:
  postgres_keycloak:
    driver: local
  postgres_stocksimapi:
    driver: local

services:

  postgres-keycloack:
    image: postgres:13-alpine
    volumes:
      - postgres_keycloak:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: pro
      POSTGRES_PASSWORD: pro

  keycloak:
    container_name: stockSim-keycloak
    image: srpoe/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloack
      DB_DATABASE: keycloak
      DB_USER: pro
      DB_SCHEMA: public
      DB_PASSWORD: pro
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres-keycloack
      - rabbitmq

  rabbitmq:
    image: srpoe/stocksimrabbitmq
    container_name: stockSim_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672

  postgres-stocksim:
    container_name: stocksim-db
    image: postgres:13-alpine
    volumes:
      - postgres_stocksimapi:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: stocksim
      POSTGRES_USER: pro
      POSTGRES_PASSWORD: pro

  stocksim-api:
    image: srpoe/stocksimapi
    ports:
      - 8070:80
    environment:
      my.keycloak.container.name: "stockSim-keycloak"
      my.postgres.container.name: "stocksim-db"
    depends_on:
      - keycloak
      - postgres-stocksim
      - rabbitmq
      - stocksim-email
      - stocksim-server-registry

  stocksim-email:
    image: srpoe/stocksimemail
    ports:
      - 8090:80
    environment:
      spring.mail.host: "YOUR SMTP EMAIL"
      spring.mail.username: "YOUR EMAIL"
      spring.mail.password: "YOUR EMAIL PASSWORD"
      my.serverregistry.container.port: "80"
    depends_on:
      - keycloak
      - postgres-stocksim
      - rabbitmq
      - stocksim-server-registry


  stocksim-server-registry:
    container_name: stockSimServerRegistry
    image: srpoe/stocksimserverregistry
    ports:
      - 8100:80
