logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

myvm.ip: 192.168.0.18

my.rabbitmq.container.name: stockSim_rabbitmq
my.serverregistry.container.name: stockSimServerRegistry
my.serverregistry.container.port: 80
my.keycloak.container.name: desktop_keycloak_1
my.postgres.container.name: stocksim

server:
  port: 80

basicAuth:
  endpoint: "/api/basicauth"

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  application:
    name: stockSim-api
  datasource:
    url: jdbc:postgresql://${my.postgres.container.name}:5432/stocksim
    username: pro
    password: pro
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${my.rabbitmq.container.name}
    port: 5672
    username: admin
    password: "{<BX>Q9samX3"
    listener:
      simple:
        prefetch: 1
      direct:
        prefetch: 1


keycloak:
  realm: stockSim
  auth-server-url: http://${my.keycloak.container.name}:8080/auth
  ssl-required: external
  resource: stocksim-api
  credentials:
    secret: 2f0fb327-4fe0-4a94-9735-f8961c262607
  use-resource-role-mappings: true
  bearer-only: false
  enable-basic-auth: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      expose: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${my.serverregistry.container.name}:${my.serverregistry.container.port}/eureka/

feign:
  hystrix:
    enabled: disabled
  client:
    config:
      default:
        readTimeout: 160000000

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10000
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      stockSim-Email:
        baseConfig: default



